### PR TITLE
Bands

### PR DESCRIPTION
**Pull request by basictom**
@utleroy
https://github.com/nashville-software-school/front-end-milestones/blob/master/2-the-static-web/exercises/SW_JS_BOYBANDS.md

### CODE REVIEW

**Comment by basictom** [comment]
@utleroy does this look good to merge?

**Comment by utleroy** [comment]
@basictom Looks good to merge. 👍  In the spirit of helpful hints and tricks to shorten your code, you don't have to concatenate <ul> and <li>. it could look something like this... veggieElement.innerHTML += '<ul><li>' + currentVeggie + '</li></ul>'; I know that it's not much but it will help you in the very near future.

**Comment by utleroy** [comment]
```veggieElement.innerHTML += '<ul><li>' + currentVeggie + '</li></ul>';```

**Comment by basictom** [comment]
@utleroy 

That is very helpful and makes a lot of sense. I think while I was baby stepping through this, it made more sense in my head to break out each element.

**Pull request merged**
